output:
  - execution
  - summary
pre-commit:
  commands:
    lint:
      run: cargo +nightly clippy --all-targets --all-features -- -D warnings
post-checkout:
  parallel: true
  jobs:
    - script: "cleanup.cjs"
      runner: node
