[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.19.2"
clap = { version = "4.5.37", features = ["derive"] }
clap_complete = "4.5.47"
dirs = "6.0.0"
duct = "0.13.7"
